services:
  mariadb:
    image: mariadb:11.1.2-jammy
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init-script/00-create-database.sql:/docker-entrypoint-initdb.d/00-create-database.sql
    environment:
      MARIADB_ROOT_PASSWORD: example

volumes:
  mariadb-data:
  